# Generated by Django 2.2.1 on 2019-06-05 20:41

from django.db import migrations, models
import manager.core.validators.validate_cpf


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190605_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[manager.core.validators.validate_cpf.validate_cpf]),
        ),
    ]
